### ISSUE TITLE
Sidebars Look Weird, And Some UX Stuff

### ISSUE THREAD

**Issue by NicksIdeaEngine** [dstrong462/numberknight#2]
This game is fantastic and beautifully written.  It's inspiring to dig through your code and feel like I'm learning.  The code is incredibly easy to follow.  Thank you!

Here are the issues I bumped into:
- Sidebars on the right and bottom of the game window appeared.  My screens are 1920 x 1080 and these sidebars appeared in maxed windows, fullscreen, and smaller windows.  Everything stayed centered and in the window, though.  Also, the bottom sidebar picks up some of the XP bar and seems to hold onto the design. Screenshot - ![sidebar example](https://cloud.githubusercontent.com/assets/7915199/21249013/1b0ef0d6-c309-11e6-9d9f-6def7c36bbe4.png)
- During the tutorial, I feel like the user hitting something on their keyboard should allow for the next part to begin.  It took me a moment to realize I typically had to click inside the black dialogue box in order to progress forward.  It's a small detail, though.
- Mid-game I clicked on settings to pause, then clicked the arrow to get back to the game.  When I tried to capture a square with the spacebar, the settings popped back up.

That's about all I picked up after a few plays.  Thanks again for the cool game and epic code :)

**Comment by dstrong462** [comment]
Scroll bars have been fixed, and appear at the edge of the screen now instead of inside the game window.

**Comment by dstrong462** [comment]
Spacebar issue had been resolved.
